export const FETCH_FILE_CONTENT_REQUEST: string = 'FETCH_FILE_CONTENT_REQUEST'
export const FETCH_FILE_CONTENT_SUCCESS: string = 'FETCH_FILE_CONTENT_SUCCESS'
export const FETCH_FILE_CONTENT_FAILURE: string = 'FETCH_FILE_CONTENT_FAILURE'